# Generated by Django 4.1.3 on 2023-01-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_model',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
