# Generated by Django 4.1.3 on 2023-01-25 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobAPP', '0002_alter_job_model_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('email', models.EmailField(max_length=254)),
                ('coverletter', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobAPP.job_model')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['created'], name='jobAPP_appl_created_151c82_idx'),
        ),
    ]
